server:
  port: 8080
  compression:
    enabled: true

hikari:
  datasource:
    poolName: ContractConnectionPool
    driverClassName: org.h2.Driver
    jdbcUrl: jdbc:h2:mem:~/test;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
    username: sa
    password:
    maximumPoolSize: 3

spring:
    h2:
      console:
        enabled: true
        path: /h2-console
        settings:
          web-allow-others: true
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.bytecode.use_reflection_optimizer: false

logging.level:
  com.zaxxer.hikari.HikariConfig: DEBUG
  org.hibernate.SQL: DEBUG
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE